export const GET_TOPICS_REQUEST = 'GET_TOPICS_REQUEST';
export const GET_TOPICS_SUCCESS = 'GET_TOPICS_SUCCESS';
export const GET_TOPICS_FAILED = 'GET_TOPICS_FAILED';

export const SUBMIT_REGISTER_REQUSET = 'SUBMIT_REGISTER_REQUSET';
export const SUBMIT_REGISTER_SUCCESS = 'SUBMIT_REGISTER_SUCCESS';
export const SUBMIT_REGISTER_FAILED = 'SUBMIT_REGISTER_FAILED';

export const LOGIN_REQUSET = 'LOGIN_REQUSET';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';

export const GET_USERINFO_REQUSET = 'GET_USERINFO_REQUSET';
export const GET_USERINFO_SUCCESS = 'GET_USERINFO_SUCCESS';
export const GET_USERINFO_FAILED = 'GET_USERINFO_FAILED';

export const AUTH_REQUSET = 'AUTH_REQUSET';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAILED = 'AUTH_FAILED';

export const CREAT_TOPIC_REQUSET = 'CREAT_TOPIC_REQUSET';
export const CREAT_TOPIC_SUCCESS = 'CREAT_TOPIC_SUCCESS';
export const CREAT_TOPIC_FAILED = 'CREAT_TOPIC_FAILED';

export const GET_TOPIC_DETAIL_REQUSET = 'GET_TOPIC_DETAIL_REQUSET';
export const GET_TOPIC_DETAIL_SUCCESS = 'GET_TOPIC_DETAIL_SUCCESS';
export const GET_TOPIC_DETAIL_FAILED = 'GET_TOPIC_DETAIL_FAILED';
export const GET_TOPIC_USER_SUCCESS = 'GET_TOPIC_USER_SUCCESS';

export const COMMIT_COMMENT_REQUSET = 'COMMIT_COMMENT_REQUSET';
export const COMMIT_COMMENT_SUCCESS = 'COMMIT_COMMENT_SUCCESS';
export const COMMIT_COMMENT_FAILED = 'COMMIT_COMMENT_FAILED';

export const GET_COLLECT_REQUEST = 'GET_COLLECT_REQUEST';
export const GET_COLLECT_SUCCESS = 'GET_COLLECT_SUCCESS';
export const GET_COLLECT_FAILED = 'GET_COLLECT_FAILED';

export const CANCEL_COLLECT_REQUEST = 'CANCEL_COLLECT_REQUEST';
export const CANCEL_COLLECT_SUCCESS = 'CANCEL_COLLECT_SUCCESS';
export const CANCEL_COLLECT_FAILD = 'CANCEL_COLLECT_FAILD';

export const UP_REPLY_REQUEST = 'UP_REPLY_REQUEST';
export const UP_REPLY_SUCCESS = 'UP_REPLY_SUCCESS';
export const UP_REPLY_FAILD = 'UP_REPLY_FAILD';

export const NO_REPLY_TOPIC_REQUEST = 'NO_REPLY_TOPIC_REQUEST';
export const NO_REPLY_TOPIC_SUCCESS = 'NO_REPLY_TOPIC_SUCCESS';
export const NO_REPLY_TOPIC_FAILED = 'NO_REPLY_TOPIC_FAILED';

export const GET_MESSAGE_COUNT_REQUEST = 'GET_MESSAGE_COUNT_REQUEST';
export const GET_MESSAGE_COUNT_SUCCESS = 'GET_MESSAGE_COUNT_SUCCESS';
export const GET_MESSAGE_COUNT_FAILED = 'GET_MESSAGE_COUNT_FAILED';

export const GET_MESSAGES_REQUEST = 'GET_MESSAGES_REQUEST';
export const GET_MESSAGES_SUCCESS = 'GET_MESSAGES_SUCCESS';
export const GET_MESSAGES_FAILED = 'GET_MESSAGES_FAILED';

export const MARK_ONE_MESSAGE_REQUEST = 'MARK_ONE_MESSAGE_REQUEST';
export const MARK_ONE_MESSAGE_SUCCESS = 'MARK_ONE_MESSAGE_SUCCESS';
export const MARK_ONE_MESSAGE_FAILED = 'MARK_ONE_MESSAGE_FAILED';

export const MARK_ALL_MESSAGE_REQUEST = 'MARK_ALL_MESSAGE_REQUEST';
export const MARK_ALL_MESSAGE_SUCCESS = 'MARK_ALL_MESSAGE_SUCCESS';
export const MARK_ALL_MESSAGE_FAILED = 'MARK_ALL_MESSAGE_FAILED';

export const DELETE_REPLY_REQUEST = 'DELETE_REPLY_REQUEST';
export const DELETE_REPLY_SUCCESS = 'DELETE_REPLY_SUCCESS';
export const DELETE_REPLY_FAILED = 'DELETE_REPLY_FAILED';

export const UPDATE_SETTING_REQUEST = 'UPDATE_SETTING_REQUEST';
export const UPDATE_SETTING_SUCCESS = 'UPDATE_SETTING_SUCCESS';
export const UPDATE_SETTING_FAILED = 'UPDATE_SETTING_FAILED';

export const UPDATE_PASSWORD_REQUEST = 'UPDATE_PASSWORD_REQUEST';
export const UPDATE_PASSWORD_SUCCESS = 'UPDATE_PASSWORD_SUCCESS';
export const UPDATE_PASSWORD_FAILED = 'UPDATE_PASSWORD_FAILED';

export const DELETE_TOPIC_REQUEST = 'DELETE_TOPIC_REQUEST';
export const DELETE_TOPIC_SUCCESS = 'DELETE_TOPIC_SUCCESS';
export const DELETE_TOPIC_FAILED = 'DELETE_TOPIC_FAILED';

export const UPDATE_TOPIC_REQUEST = 'UPDATE_TOPIC_REQUEST';
export const UPDATE_TOPIC_SUCCESS = 'UPDATE_TOPIC_SUCCESS';
export const UPDATE_TOPIC_FAILED = 'UPDATE_TOPIC_FAILED';

export const INIT_TOPIC_DETAIL = 'INIT_TOPIC_DETAIL';

export const INIT_USER_INFO = 'INIT_USER_INFO';